// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTs9UaBWLlCsi75ucjx9x89t_1coZa8o',
    appId: '1:200338959567:web:655949431d72a567165bba',
    messagingSenderId: '200338959567',
    projectId: 'knowledge-a2d0e',
    authDomain: 'knowledge-a2d0e.firebaseapp.com',
    storageBucket: 'knowledge-a2d0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALoyaUkSIlAlVQXM9JgTcsFof-f78yYIw',
    appId: '1:200338959567:android:f42f546fcf28743d165bba',
    messagingSenderId: '200338959567',
    projectId: 'knowledge-a2d0e',
    storageBucket: 'knowledge-a2d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6S1peiHtTdmGwwdmyIQBtEwpure2DSmo',
    appId: '1:200338959567:ios:13e7c16d86a07dc9165bba',
    messagingSenderId: '200338959567',
    projectId: 'knowledge-a2d0e',
    storageBucket: 'knowledge-a2d0e.firebasestorage.app',
    iosClientId: '200338959567-4bvb76crrdcjjtnvmlqog0s4f8vl2219.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms',
  );
}
